### PR TITLE
Implemented the feature #32

### PR DESCRIPTION
**Pull request by Vest**
Hello @Nilhcem,

I have added the feature being requested in #32. Could you please review my changes and give me any feedback regarding them?

Kind regards,
Vest

### CODE REVIEW

**Comment by Nilhcem** [comment]
Thanks,
I'll check this when I have some time (hopefully soon)

**Comment by Nilhcem** [comment]
Perfect, thanks!

**Comment by Vest** [comment]
Thanks for the merge.
Was everything fine with the code?

**Comment by Nilhcem** [comment]
I could not do it better, 

I wanted to see how the i18n behaves when there's no translation key specified for a give language (the `startsrv.err.invalidHost` added key) (e.g. if it uses english by default) and finally no, the error message is empty, so I added the translations for the other languages to make sure it works well

**Pull request closed without merging**
