### PR TITLE
Add docker

### PR DESCRIPTION
**Pull request by evrycollin**
I like FakeSmtp in my dev environements. Tiny and simple !

I would like to have it running as a Docker container.

Here 2 examples :

- download distribution and run it as a container
- build application and container with maven

### CODE REVIEW

**Comment by evrycollin** [comment]
hello
please remove this line from readme file : 

    git checkout remotes/origin/add-docker

I've added it in order to build my on pullbranch

best regards

Evry

**Comment by evrycollin** [comment]
a nice idea would be to create a Nilhcem/FakeSMTP DockerHub repository and push an image that user can directly use rather the building it :)

**Comment by evrycollin** [comment]
pulled repository evrycollin/FakeSMTP  deleted

**Comment by evrycollin** [comment]
wrong url for readme :

    Build from source / Get sources from GitHub: Dockerfile

use : 

      https://github.com/Nilhcem/FakeSMTP/blob/master/src/main/docker/Dockerfile

rather than : 

     https://github.com/Nilhcem/FakeSMTP/blob/master/src/main/docker/Dockerfile

**Comment by Nilhcem** [comment]
Many thanks,
I'll consider for the image in the DockerHub repo.

**Pull request closed without merging**
