### PR TITLE
Feature for Issue #25

### PR DESCRIPTION
**Pull request by Vest**
Hello @Nilhcem,

Here is the first version of the requested feature #25. This is the first time, when I code something for an open source project. Any suggestions, advices, improvements proposals are welcome.

The commit 3367f11 contains the description of my changes. In addition, I have decided to add the final modifier to a couple of internal variables.

I have tried to follow the style of the code that you have.

p.s. just in case, I have added an option to enable/disable the system tray feature in the configuration file.

Kind regards,
Vest

### CODE REVIEW

**Comment by Vest** [comment]
Small addition, maybe it makes sense to close the application, when the "X" button is clicked (or the Exit menu item is selected), but when the window is minimized - hide it and create the tray icon.

**Comment by Nilhcem** [comment]
Many thanks for your smartly implemented Pull Request!

I've merged it but have *temporarily* disabled the `application.tray.use` property (set to false), as the tray feature does not work well on GNOME shell (and some other desktop managers).
See http://stackoverflow.com/questions/29995727/java-systemtray-icon-does-not-always-work

**Comment by Vest** [comment]
@Nilhcem, thank you for the merge. I will take a look at the behavior, what my code does.
Do you have other suggestions what else I can add? E.g. create checkbox that helps to enable/disable the tray.
Or, what worries me is that the window is always minimized, if you try to close it. Who knows, maybe it is useless, and I have to minimize the window into the tray, when the user clicks a corresponding button only?

**Comment by Nilhcem** [comment]
In terms of features it seems fine. I don't see anything else to add.

I agree the  'close-to-put-to-system-tray' is quite disturbing but may be common for Windows users.
Maybe we could just enable this feature for Windows users, so that we could bypass the gnome/kde issue in the same time

**Comment by Vest** [comment]
Ok, I will check this. I have an Ubuntu machine.
By the way, I have a short questions regarding the removal of **final** keywords. What was the intention of doing this?
When I was writing them, I assumed that it makes the code more defensive against accident changes of references.

**Comment by Nilhcem** [comment]
I mostly stayed consistent with the existing code base (there's a lot of things I have done and regret, mostly the tab indentation).
You may be right in adding them.
My point of view is that the final keywords are great when making an API, less for an open source application where I prefer to have less code.
I'm not keen on defensive programming and prefer to have smart PRs that do not alter the reference of a method parameter, for instance.

**Comment by Vest** [comment]
Ok, clear.
Thanks.

**Comment by Vest** [comment]
I found what happened with the frame in Linux: https://community.oracle.com/thread/1352367
I have exactly the same behavior as written in the thread - the Iconify event is called twice.
I will probably create a new issue in future and investigate how I can fix it (without using some "trigger" variable, or time).

**Pull request merged**
